### ISSUE TITLE
Header design (with logo)

### ISSUE THREAD

**Issue by leinadpb** [leinadpb/provisio#13]

**Comment by shepherdless** [comment]
On review.

**Comment by leinadpb** [comment]
@WanderingRonin do you Zenhub installed? If don't, install it. Then you only have to drag the ticket to the column "in progress" when you start working on it. When you're done, drag it to "Review".

**Comment by shepherdless** [comment]
Yes it is installed, but I seldom use it... I will use it from now on lol
