### ISSUE TITLE
Tabs design (text with icons)

### ISSUE THREAD

**Issue by leinadpb** [leinadpb/provisio#14]
Remember, "add product" tab **should only show** if the user is logged in as "provider".

**Comment by shepherdless** [comment]
Partially done.

The only thing left to do is to add the boolean condition on whether the user is logged in as a provider to show the add product tab or the user is just a normal user and cannot see the add product tab, condition which is done after the user-types are updated

**Comment by leinadpb** [comment]
Doesn't matter. We should have the functionality ready. Just add the boolean to the .ts file and put it "true" by default.

**Comment by shepherdless** [comment]
Alright, on it.
